### ISSUE TITLE
Mover informações de contato do órgão

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#402]
Percebemos que o conteúdo do contato dos órgãos existentes estão atualmente dentro do application.yaml do Portal de Serviços. Acontece que no Editor de órgãos, pedimos para que o contato do órgão, seja preenchido lá.

Precisamos mover as informações de contato (abaixo) que estão no aplication.yaml para dentro do Editor. 

@almeidafab @mformiga @gustavo-freitas, podemos realizar esta mudança de conteúdo? A ideia é apenas transportar a informação para o local correto. Aguardamos. 

```
 conteudo:
    ouvidorias:
      arquivo-nacional-an: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/arquivo-nacional-an
      banco-central-do-brasil-bcb: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/bancos/banco-central-do-brasil-bacen
      comissao-de-anistia-cma: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-justica-mj
      companhia-nacional-de-abastecimento-conab: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/outras-estatais/companhia-nacional-de-abastecimento-conab
      conselho-administrativo-de-defesa-economica-cade: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-justica-mj
      defensoria-publica-da-uniao-dpu: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/defensoria-publica-da-uniao-dpu
      departamento-de-policia-federal-dpf: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/departamento-de-policia-federal-dpf
      departamento-de-policia-rodoviaria-federal-dprf: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/departamento-de-policia-rodoviaria-federal-dprf
      empresa-brasileira-de-infraestrutura-aeroportuaria-infraero: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/outras-estatais/empresa-brasileira-de-infraestrutura-aeroportuaria-infraero
      fundacao-nacional-do-indio-funai: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/outras-autarquias/fundacao-nacional-do-indio-funai
      instituto-nacional-de-meteorologia-inmet: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-agricultura-pecuaria-e-abastecimento-mapa
      instituto-nacional-do-seguro-social-inss: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-previdencia-social-mps
      ministerio-da-agricultura-pecuaria-e-abastecimento-mapa: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-agricultura-pecuaria-e-abastecimento-mapa
      ministerio-da-fazenda-mf: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-fazenda-mf
      ministerio-da-justica-mj: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-justica-mj
      ministerio-da-pesca-e-aquicultura-mpa: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-pesca-e-aquicultura-mpa
      ministerio-da-previdencia-social-mps: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-previdencia-social-mps
      ministerio-da-saude-ms: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-saude-ms
      ministerio-do-desenvolvimento-agrario-mda: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-do-desenvolvimento-agrario-mda
      ministerio-do-desenvolvimento-social-e-combate-a-fome-mds: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-do-desenvolvimento-social-e-combate-a-fome-mds
      ministerio-do-planejamento-orcamento-e-gestao-mpog: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-do-planejamento-orcamento-e-gestao-mpog
      ministerio-do-trabalho-e-emprego-mte: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-do-trabalho-e-emprego-mte
      ministerio-do-turismo-mtur: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-do-turismo-mtur
      secretaria-da-receita-federal-do-brasil-rfb: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-fazenda-mf
      secretaria-de-aviacao-civil-sac: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/secretaria-de-aviacao-civil-sac
      secretaria-de-planejamento-e-investimentos-estrategicos-spi: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-do-planejamento-orcamento-e-gestao-mpog
      secretaria-do-patrimonio-da-uniao-spu-mp: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-do-planejamento-orcamento-e-gestao-mpog
      secretaria-nacional-de-justica-snj: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-justica-mj
      secretaria-nacional-de-politicas-sobre-drogas-senad: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-justica-mj
      secretaria-nacional-de-seguranca-publica-senasp: http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/adm_direta/ministerio-da-justica-mj
    sitesOficiais:
      arquivo-nacional-an: http://www.arquivonacional.gov.br/
      banco-central-do-brasil-bcb: http://www.bcb.gov.br/
      comissao-de-anistia-cma: http://portal.mj.gov.br/anistia/
      companhia-nacional-de-abastecimento-conab: http://www.conab.gov.br/
      conselho-administrativo-de-defesa-economica-cade: http://www.cade.gov.br/
      defensoria-publica-da-uniao-dpu: http://www.dpu.gov.br/
      departamento-de-policia-federal-dpf: http://www.dpf.gov.br/
      departamento-de-policia-rodoviaria-federal-dprf: https://www.prf.gov.br/portal/
      empresa-brasileira-de-infraestrutura-aeroportuaria-infraero: http://www.infraero.gov.br/
      fundacao-nacional-do-indio-funai: http://www.funai.gov.br/
      instituto-nacional-de-meteorologia-inmet: http://www.inmet.gov.br/
      instituto-nacional-do-seguro-social-inss: http://www.inss.gov.br/
      ministerio-da-agricultura-pecuaria-e-abastecimento-mapa: http://www.agricultura.gov.br/ministerio
      ministerio-da-educacao-mec: http://mec.gov.br/
      ministerio-da-fazenda-mf: http://www.fazenda.gov.br/
      ministerio-da-justica-mj: http://www.justica.gov.br/
      ministerio-da-pesca-e-aquicultura-mpa: http://www.mpa.gov.br/
      ministerio-da-previdencia-social-mps: http://mps.gov.br/
      ministerio-da-saude-ms: http://portalsaude.saude.gov.br/
      ministerio-do-desenvolvimento-agrario-mda: http://www.mda.gov.br/
      ministerio-do-desenvolvimento-social-e-combate-a-fome-mds: http://mds.gov.br/
      ministerio-do-planejamento-orcamento-e-gestao-mpog: http://www.planejamento.gov.br/
      ministerio-do-trabalho-e-emprego-mte: http://portal.mte.gov.br/portal-mte/
      ministerio-do-turismo-mtur: http://www.turismo.gov.br/turismo/home.html
      secretaria-da-receita-federal-do-brasil-rfb: http://idg.receita.fazenda.gov.br/
      secretaria-de-aviacao-civil-sac: http://www.aviacaocivil.gov.br/
      secretaria-nacional-de-justica-snj: http://portal.mj.gov.br/data/Pages/MJDE2A290DITEMIDC811B50F3FA34D6AA46F27CC110930B1PTBRIE.htm
      secretaria-nacional-de-politicas-sobre-drogas-senad: http://portal.mj.gov.br/senad/
      secretaria-nacional-de-seguranca-publica-senasp: http://portal.mj.gov.br/main.asp?View={1BFF9F1B-2ECD-4A25-9976-661FB5A66624}&BrowserType=NN&LangID=pt-br&params=itemID%3D%7B540715BB-1C9B-47D3-9549-9FA38E3E99FA%7D%3B&UIPartUID=%7B2868BA3C-1C72-4347-BE11-A26F70F4CB26%7D
    telefones:
      ministerio-da-educacao-mec: "0800 61 61 61"
      ministerio-da-saude-ms: "136"
      ministerio-do-desenvolvimento-social-e-combate-a-fome-mds: "0800 707 2003"
      instituto-nacional-do-seguro-social-inss: "135"
      ministerio-da-previdencia-social-mps: "135"
      secretaria-da-receita-federal-do-brasil-rfb: "146 para ligações realizadas no Brasil, ou (+55) (11) 3003-0146 para chamadas originadas do exterior."
      ministerio-da-fazenda-mf: "0800 702 1111"
```
